default_index:
  path: /
  defaults: { _controller: "AppBundle:Default:index" }
  methods: GET

default_index:
  path: /pruebas
  defaults: { _controller: "AppBundle:Default:pruebas" }
  methods: GET